---
driver_config:
  openstack_username: <%= ENV['OS_USERNAME'] %>
  openstack_api_key: <%= ENV['OS_PASSWORD'] %>
  openstack_auth_url: <%= "#{ENV['OS_AUTH_URL']}/tokens" %>
  key_name: <%= ENV['OS_SSH_KEYPAIR'] %>
  private_key_path: <%= ENV['OS_PRIVATE_SSH_KEY'] %>
  public_key_path: <%= ENV['OS_PUBLIC_SSH_KEY'] %>
  openstack_tenant: <%= ENV['OS_TENANT_NAME'] %>
  floating_ip_pool: <%= ENV['OS_FLOATING_IP_POOL'] %>
  flavor_ref: <%= ENV['OS_FLAVOR_REF'] %>
  # Only use the following if you need to open up firewall ports
  security_groups:
    - <%= ENV['OS_SECURITY_GROUP_NO_FIREWALL'] %>

provisioner:
  name: chef_solo

platforms:
  - name: centos-6.7
    driver_plugin: openstack
    driver_config:
      username: centos
      image_ref: "CentOS 6.7"
  - name: centos-7.1
    driver_plugin: openstack
    driver_config:
      username: centos
      image_ref: "CentOS 7.1"

suites:
  - name: default
    data_bags_path: test/integration/data_bags
    run_list:
      - recipe[osl-jenkins::default]
  - name: master
    run_list:
      - recipe[osl-jenkins::master]
      - recipe[jenkins::java]
      - recipe[jenkins::master]
  - name: haproxy
    data_bags_path: test/integration/data_bags
    encrypted_data_bag_secret_key_path: test/integration/encrypted_data_bag_secret
    run_list:
      - recipe[certificate::manage_by_attributes]
      - recipe[osl-jenkins::haproxy]
      - recipe[osl-haproxy::default]
    attributes:
      certificate:
        -
          snakeoil:
            cert_path: /etc/pki/tls
            cert_file: wildcard.pem
            key_file: wildcard.key
            chain_file: wildcard-bundle.crt
            combined_file: true
  - name: chef_backup
    run_list:
      - recipe[osl-jenkins::chef_backup]
    attributes:
      jenkins:
         master:
           user: 'centos'
           group: 'centos'
  - name: chef_ci_cookbook_template
    run_list:
      - recipe[osl-jenkins::chef_ci_cookbook_template]
  - name: plugins
    run_list:
      - recipe[osl-jenkins::master]
      - recipe[jenkins::java]
      - recipe[jenkins::master]
      - recipe[osl-jenkins::plugins]
