---
driver:
  flavor_ref: 'm1.medium'

provisioner:
  name: chef_solo
  encrypted_data_bag_secret_key_path: test/integration/encrypted_data_bag_secret
  data_bags_path: test/integration/data_bags
  attributes:
    certificate:
      - snakeoil:
          cert_path: "/etc/pki/tls"
          cert_file: wildcard.pem
          key_file: wildcard.key
          chain_file: wildcard-bundle.crt
          combined_file: true

suites:
  - name: default
    run_list:
      - recipe[osl-jenkins::default]
  - name: master
    run_list:
      - recipe[osl-jenkins::master]
    attributes:
      osl-jenkins:
        credentials:
          ssh:
            alfred:
              user: 'alfred'
              private_key: "-----BEGIN RSA PRIVATE KEY-----\nMIIBywIBAAJhAMSrk3a8XLZW0UdtDS49VdaPRskJtrCIPfJy9ZWMA5LyCob+e0DW\nRN33vA+x0wmw4hievTtpNDbntGpN+rnq5Xl/Nlpo+rxa+eLj3anU030gYYKFc0K0\nC7wu+EtZ6ZvKpQIDAQABAmA9cxKfTdl2C4hWVeeBZB627IuEcymG3PrmDy9Wq6nO\nNxw887SVHJ3l8OrsyHYVGBPwJXd2dfrFVwjdD6UeHXIqx2Lb9I1CzYVa7RkGL1ZU\nTAb1JdDf5vZFpELlkqczcp0CMQD2JfP/r55uRowVUs9+c7MN8J5Cg4YXDw6MQgpE\nE3+x92xM3TQzGM3PNeNpuby0fx8CMQDMiqsnoQQe8dEbAPetgBHZncA4TvS1w6KF\nq72HOwa2PW7DQXsiwuIN/wNhgALSMbsCMQCJJT5c8NnCMZZtbxVjLE3Qb4eOIb/9\naws9BLK5mW+llekGrp0d9yz8zdammrFUlBsCMF3qEZn5gVXf+/3lHNOp6Qg9OUPh\nZNSMRfQQHc6YmIVWgaPfTfVw+7AnddrvltwB/wIxAL+Q5ZXtglRrFFoYNdHplHb+\nBPgWsltlXXY1BmOEUWgAZLEs+tvSV8enIVlUSZ+Lxg==\n-----END RSA PRIVATE KEY-----"

  - name: haproxy
    encrypted_data_bag_secret_key_path: test/integration/encrypted_data_bag_secret
    run_list:
      - recipe[certificate::manage_by_attributes]
      - recipe[osl-jenkins::haproxy]
      - recipe[osl-haproxy::default]
  - name: chef_backup
    run_list:
      - recipe[osl-jenkins::chef_backup]
    attributes:
      jenkins:
        master:
          user: centos
          group: centos
  - name: chef_ci_cookbook_template
    run_list:
      - recipe[osl-jenkins::chef_ci_cookbook_template]
  - name: plugins
    run_list:
      - recipe[osl-jenkins::master]
      - recipe[osl-jenkins::plugins]
  - name: ftp
    run_list:
      - recipe[osl-jenkins::ftp]

  # In order to properly test GitHub integration, you must export the
  # GITHUB_USER and GITHUB_TOKEN env vars in your shell before you converge
  # this suite.  You'll need to use an account/token that has permission to
  # pull/push private repos and create webhooks.  You also need to choose a
  # random TRIGGER_TOKEN string.  This is what GitHub will use to trigger
  # Jenkins jobs remotely.
  #
  # For example:
  #   $ export GITHUB_USER=examplegithubuser
  #   $ export GITHUB_TOKEN=examplegithubtoken
  #   $ export TRIGGER_TOKEN=exampletriggertoken
  #   $ kitchen converge cookbook-uploader-centos-72
  #
  # It's worth noting that security (i.e. logging in to Jenkins) is not enabled
  # by default, and so remotely triggered build configuration will not appear
  # when configuring jobs.  It will, however, still be set.  If you enable
  # user/pass security, then the Jenkins cookbook will not be able to update
  # jobs, since it then has to log in.  To fix this, you must create a user
  # account for the cookbook and export the JENKINS_USER and JENKINS_PASS env
  # vars in addition to the others.
  - name: cookbook-uploader
    encrypted_data_bag_secret_key_path: test/integration/encrypted_data_bag_secret
    run_list:
      - recipe[osl-jenkins::cookbook_uploader]
    provisioner: chef_zero
    driver:
      security_groups:
        - default
        - github
    attributes:
      osl-jenkins:
        cookbook_uploader:
          authorized_teams:
            - 'osuosl-cookbooks/staff'
          chef_repo: 'osuosl/chef-repo'
          default_environments:
            - openstack_mitaka
            - phase_out_nginx
            - phpbb
            - production
            - testing
            - workstation
          override_repos:
            - test-cookbook
          github_insecure_hook: true
          do_not_upload_cookbooks: true
        credentials:
          git:
            cookbook_uploader:
              user: <%= ENV['GITHUB_USER'] %>
              token: <%= ENV['GITHUB_TOKEN'] %>
          jenkins:
            cookbook_uploader:
              user: <%= ENV['JENKINS_USER'] %>
              api_token: <%= ENV['JENKINS_PASS'] %>
              trigger_token: <%= ENV['TRIGGER_TOKEN'] %>
      jenkins:
        master:
          listen_address: '0.0.0.0'
  # See documentation from cookbook-uploader suite on how to run this suite
  - name: jenkins1
    encrypted_data_bag_secret_key_path: test/integration/encrypted_data_bag_secret
    run_list:
      - recipe[osl-jenkins::jenkins1]
    driver:
      security_groups:
        - default
        - github
    attributes:
      osl-jenkins:
        cookbook_uploader:
          override_repos:
            - test-cookbook
          github_insecure_hook: true
          do_not_upload_cookbooks: true
        credentials:
          git:
            cookbook_uploader:
              user: <%= ENV['GITHUB_USER'] %>
              token: <%= ENV['GITHUB_TOKEN'] %>
            bumpzone:
              user: <%= ENV['GITHUB_USER'] %>
              token: <%= ENV['GITHUB_TOKEN'] %>
            github_comment:
              user: <%= ENV['GITHUB_USER'] %>
              token: <%= ENV['GITHUB_TOKEN'] %>
            site_pr_builder:
              user: <%= ENV['GITHUB_USER'] %>
              token: <%= ENV['GITHUB_TOKEN'] %>
          jenkins:
            cookbook_uploader:
              user: <%= ENV['JENKINS_USER'] %>
              api_token: <%= ENV['JENKINS_PASS'] %>
              trigger_token: <%= ENV['TRIGGER_TOKEN'] %>
            bumpzone:
              user: <%= ENV['JENKINS_USER'] %>
              api_token: <%= ENV['JENKINS_PASS'] %>
              trigger_token: <%= ENV['TRIGGER_TOKEN'] %>
            github_comment:
              user: <%= ENV['JENKINS_USER'] %>
              api_token: <%= ENV['JENKINS_PASS'] %>
              trigger_token: <%= ENV['TRIGGER_TOKEN'] %>
            site_pr_builder:
              user: <%= ENV['JENKINS_USER'] %>
              api_token: <%= ENV['JENKINS_PASS'] %>
              trigger_token: <%= ENV['TRIGGER_TOKEN'] %>
      jenkins:
        master:
          listen_address: '0.0.0.0'
  - name: bumpzone
    encrypted_data_bag_secret_key_path: test/integration/encrypted_data_bag_secret
    run_list:
      - recipe[osl-jenkins::bumpzone]
    provisioner: chef_zero
    driver:
      security_groups:
        - default
        - github
    attributes:
      osl-jenkins:
        bumpzone:
          github_url: 'https://github.com/osuosl/zonefiles-test.git'
        credentials:
          git:
            bumpzone:
              user: <%= ENV['GITHUB_USER'] %>
              token: <%= ENV['GITHUB_TOKEN'] %>
          jenkins:
            bumpzone:
              user: <%= ENV['JENKINS_USER'] %>
              api_token: <%= ENV['JENKINS_PASS'] %>
              trigger_token: <%= ENV['TRIGGER_TOKEN'] %>
      jenkins:
        master:
          listen_address: '0.0.0.0'
  - name: github_comment
    run_list:
      - recipe[osl-jenkins::github_comment]
    encrypted_data_bag_secret_key_path: test/integration/encrypted_data_bag_secret
    provisioner: chef_zero
    driver:
      security_groups:
        - default
        - github
    attributes:
      osl-jenkins:
        github_comment:
          override_repos:
            - test-cookbook
          github_insecure_hook: true
        credentials:
          git:
            github_comment:
              user: <%= ENV['GITHUB_USER'] %>
              token: <%= ENV['GITHUB_TOKEN'] %>
          jenkins:
            github_comment:
              user: <%= ENV['JENKINS_USER'] %>
              api_token: <%= ENV['JENKINS_PASS'] %>
              trigger_token: <%= ENV['TRIGGER_TOKEN'] %>
      jenkins:
        master:
          listen_address: '0.0.0.0'
  - name: site_pr_builder
    run_list:
      - recipe[osl-jenkins::site_pr_builder]
    encrypted_data_bag_secret_key_path: test/integration/encrypted_data_bag_secret
    provisioner: chef_zero
    driver:
      security_groups:
        - default
        - github
    attributes:
      osl-jenkins:
        github_comment:
          override_repos:
            - test-cookbook
          github_insecure_hook: true
        credentials:
          git:
            site_pr_builder:
              user: <%= ENV['GITHUB_USER'] %>
              token: <%= ENV['GITHUB_TOKEN'] %>
          jenkins:
            site_pr_builder:
              user: <%= ENV['JENKINS_USER'] %>
              api_token: <%= ENV['JENKINS_PASS'] %>
              trigger_token: <%= ENV['TRIGGER_TOKEN'] %>
      jenkins:
        master:
          listen_address: '0.0.0.0'
  - name: powerci 
    run_list:
      - recipe[osl-jenkins::powerci]
  - name: packer_pipeline
    encrypted_data_bag_secret_key_path: test/integration/encrypted_data_bag_secret
    data_bags_path: test/integration/data_bags
    run_list:
      - recipe[osl-jenkins::packer_pipeline]
    excludes:
      - centos-6.9
