---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  encrypted_data_bag_secret_key_path: test/integration/encrypted_data_bag_secret
  data_bags_path: test/integration/data_bags

platforms:
  - name: centos-6.7
  - name: centos-7.1

suites:
  - name: default
    run_list:
      - recipe[osl-jenkins::default]
  - name: master
    run_list:
      - recipe[osl-jenkins::master]
      - recipe[jenkins::java]
      - recipe[jenkins::master]
  - name: haproxy
    run_list:
      - recipe[certificate::manage_by_attributes]
      - recipe[osl-jenkins::haproxy]
      - recipe[osl-haproxy::default]
    attributes:
      certificate:
        -
          snakeoil:
            cert_path: /etc/pki/tls
            cert_file: wildcard.pem
            key_file: wildcard.key
            chain_file: wildcard-bundle.crt
            combined_file: true
  - name: chef_backup
    run_list:
      - recipe[osl-jenkins::chef_backup]
    attributes:
      jenkins:
         master:
           user: 'centos'
           group: 'centos'
  - name: plugins
    run_list:
      - recipe[osl-jenkins::master]
      - recipe[jenkins::java]
      - recipe[jenkins::master]
      - recipe[osl-jenkins::plugins]
  - name: chef_ci_cookbook_template
    run_list:
      - recipe[osl-jenkins::chef_ci_cookbook_template]
