---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: centos-6.6

suites:
  - name: default
    run_list:
      - recipe[osl-jenkins::default]
  - name: chef_backup
    run_list:
      - recipe[osl-jenkins::chef_backup]
    attributes:
      jenkins:
         master:
           user: 'centos'
           group: 'centos'
