AllCops:
  TargetChefVersion: 16.latest
Chef/Modernize/FoodcriticComments:
  Enabled: true
Chef/Style/CopyrightCommentFormat:
  Enabled: true

Style/MutableConstant:
  Exclude:
    - 'spec/spec_helper.rb'

Metrics/AbcSize:
  Max: 31.11
  Exclude:
    - 'libraries/default.rb'
    - 'files/default/lib/packer_pipeline.rb'

Metrics/CyclomaticComplexity:
  Exclude:
    - 'files/default/lib/packer_pipeline.rb'

Metrics/PerceivedComplexity:
  Exclude:
    - 'files/default/lib/packer_pipeline.rb'

Metrics/ModuleLength:
  Max: 150
  Exclude:
    - 'libraries/docker.rb'

Metrics/MethodLength:
  Max: 40
  Exclude:
    - 'libraries/default.rb'

Style/ClassAndModuleChildren:
  Exclude:
    - 'recipes/powerci.rb'
    - 'recipes/ibmz_ci.rb'
Style/Documentation:
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'
    - 'libraries/docker.rb'
    - 'libraries/openstack.rb'
    - 'libraries/github_oauth.rb'
    - 'recipes/powerci.rb'
    - 'recipes/ibmz_ci.rb'
